return {
  -- {
  --   "nvim-treesitter/nvim-treesitter",
  --   branch = "main",
  --   build = ":TSUpdate",
  --   config = function()
  --     local ts = require("nvim-treesitter")
  --     ts.install({
  --       "bash",
  --       "ruby", 
  --       "html",
  --       "css",
  --       "scss",
  --       "javascript",
  --       "typescript",
  --       "json",
  --       "lua",
  --     })
  --   end
  -- }
}
